CREATE TABLE tts_text_replacements (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    source_text VARCHAR(100) NOT NULL,
    target_text VARCHAR(100) NOT NULL DEFAULT '',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
